server:
  port: 30000
#spring:
#  redis:
#    database: 9
#    host: 192.168.1.25
#    port: 6379
#    password: 12345678
#    timeout: 1000
#    jedis:
#      pool:
#        min-idle: 1
#        max-idle: 10
#        max-active: 20
#        max-wait: 1000